package creativity

import (
	"context"
	"fmt"
	"strings"
)

// generateSuggestion calls the AI to produce a suggestion using the project context.
func (e *CreativityEngine) generateSuggestion(ctx context.Context, projectCtx *ProjectContext) (*Suggestion, error) {
	prompt := buildPrompt(projectCtx)
	suggestion, err := e.ai.GenerateSuggestion(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("generating suggestion: %w", err)
	}
	return suggestion, nil
}

// isDuplicate checks if a suggestion duplicates an existing issue or rejected idea.
func (e *CreativityEngine) isDuplicate(suggestion *Suggestion, projectCtx *ProjectContext) bool {
	title := strings.ToLower(suggestion.Title)

	// Check against pending suggestions.
	for _, issue := range projectCtx.PendingIdeas {
		if strings.Contains(title, strings.ToLower(issue.Title)) ||
			strings.Contains(strings.ToLower(issue.Title), title) {
			return true
		}
	}

	// Check against open issues.
	for _, issue := range projectCtx.OpenIssues {
		if strings.Contains(title, strings.ToLower(issue.Title)) ||
			strings.Contains(strings.ToLower(issue.Title), title) {
			return true
		}
	}

	// Check against rejection cache.
	if e.rejectionCache.Contains(suggestion.Title) {
		return true
	}

	return false
}

// createSuggestionIssue creates a GitHub issue for the suggestion with the agent:suggestion label.
func (e *CreativityEngine) createSuggestionIssue(ctx context.Context, suggestion *Suggestion) error {
	body := fmt.Sprintf("## Suggested Improvement\n\n%s\n\n---\n*Automatically generated by agent `%s` during idle creative thinking.*",
		suggestion.Body, e.agentID)

	_, err := e.gh.CreateIssue(ctx, suggestion.Title, body, []string{labelSuggestion})
	if err != nil {
		return fmt.Errorf("creating suggestion issue: %w", err)
	}
	return nil
}
